### ISSUE TITLE
python api cannot handle annotation error

### ISSUE THREAD

**Issue by Figora** [pdollar/coco#1]
It seems that there is something wrong with the annotation of 'COCO_train2014_000000255018.jpg'. I try to use python api 'segToMask' to generate the binary mask of this image, line 368 of coco.py throws an exception.  I think we could add some code to avoid this. Maybe we could change line 367 of coco.py to something like this.

 rr, cc = polygon(np.array(s[1:N:2]).clip(max = (h - 1)), np.array(s[0:N:2]).clip(max = (w - 1))) # (y, x)

**Comment by tylin** [comment]
Thanks for catching the exception.
The code has been updated according to the advice.
