### ISSUE TITLE
LuaAPI supports parsing large instances_train2014.json

### ISSUE THREAD

**Issue by pinglin** [pdollar/coco#17]
I am wondering if LuaAPI is gonna support parsing large json file or not? Currently parsing `instances_train2014.json` (354MB) will cause LuaJIT out of memory. Also would like to know if LuaAPI will be as complete as Python or Matlab APIs in the future. Thanks.

**Comment by pdollar** [comment]
Good questions.

Yeah, LuaJIT sucks in this regards. You have two options: do the initial conversion in Lua (not LuaJIT) or I also noticed that while on Linux it runs out of memory on my Mac it does not. Anyway, once you do the initial conversion and it saves the T7 file, after that it won't need much memory so you can run it in LuaJIT.

We don't have plans to further extend the LuaApi (for example, we don't plan on adding evaluation code to the LuaApi). For this please use the Python or Matlab APIs. It's also possible to create a python bridge from Lua (but we won't be offering support for how to do this).

Thanks.

**Comment by shijx12** [comment]
Specifically, 
```
cd ~/torch  # your torch installation path
./clean.sh
TORCH_LUA_VERSION=LUA52 ./install.sh  # reinstall torch with lua52 instead of luajit
```

Then it works. Don't forget to reinstall cocoApi using luarocks.
