### ISSUE TITLE
 attempt to index global 'torch' (a nil value)

### ISSUE THREAD

**Issue by xhpohanka** [pdollar/coco#21]
Hi,

I was able to use coco in Python but I have no success with lua following your readme. Can you please tell me what I'm doing wrong? It would be probably some basic thing in configuration, but I'm new to lua and torch enviroment...

```
lua5.1 LuaAPI/cocoDemo.lua 
lua5.1: ...e/test/torch/install/share/lua/5.1/coco/CocoApi.lua:45: attempt to index global 'torch' (a nil value)
stack traceback:
	...e/test/torch/install/share/lua/5.1/coco/CocoApi.lua:45: in main chunk
	[C]: in function 'require'
	...home/test/torch/install/share/lua/5.1/coco/init.lua:11: in main chunk
	[C]: in function 'require'
	LuaAPI/cocoDemo.lua:2: in main chunk
	[C]: ?
```

**Comment by tylin** [comment]
It seems you may not have Torch installed.
You can install Torch from here: http://torch.ch/docs/getting-started.html

**Comment by xhpohanka** [comment]
Unfortunatelly this is not the case, torch is installed and I'm getting the same error mesage by calling `lua5.1` from system or `qlua` and `luajit` from torch installation.

`~/torch/install/bin/torch-activate` was sourced...

All this is happening on up to date Arch Linux
