### ISSUE TITLE
analyze  function in python api

### ISSUE THREAD

**Issue by wenmengzhou** [pdollar/coco#211]
Using matlab api, we can call E.analyze() to plot detailed analysis of errors.  on the website of http://cocodataset.org/#detection-eval, it is said  python code of analyze function will come soon,  but when?

**Comment by Eldad27** [comment]
@wenmengzhou Did you get any update on this? Something of interest to me as well.

**Comment by mburges-cvl** [comment]
@wenmengzhou @Eldad27 Is there any update to this issue?

**Comment by wenmengzhou** [comment]
> @wenmengzhou @Eldad27 Is there any update to this issue?

I have implemented this function in my own repository

https://github.com/wenmengzhou/cocoapi
