### ISSUE TITLE
Compile the PythonAPI on Windows

### ISSUE THREAD

**Issue by lasandcris** [pdollar/coco#22]
I'm having problems running the make file on windows. Can it be the c99 flag for the compiler? I can't even run the "extra_compile_args=["-Wno-cpp", "-Wno-unused-function", "-std=c99"]" in the setup.py. When I pass through those args I can see a lot of c specific errors in the console.

Does anyone have any solution to this?

thanks.

**Comment by lasandcris** [comment]
found my answer from a previous issue. thanks

**Comment by LeeKyungMoon** [comment]
Can you explain how you solved this problem? I'm confronting exactly the same issue.
Thanks.
