### ISSUE TITLE
README.txt update needed - Images not in coco/images/

### ISSUE THREAD

**Issue by ProgramItUp** [pdollar/coco#24]
The page https://github.com/pdollar/coco says 

> MS COCO API - http://mscoco.org/
> Please download, unzip, and place the images in: coco/images/
> Please download and place the annotations in: coco/annotations/

The URL http://mscoco.org/coco/images/ generates the following error:
Not Found
The requested URL /coco/images/ was not found on this server.

It looks like the base URL has changed.  For, example the 2015 Testing images is at http://msvocds.blob.core.windows.net/coco2015/test2015.zip

**Comment by tylin** [comment]
"Please download, unzip, and place the images in: coco/images/"
This means to download the zip file and unzip it to local "coco/images" directory.

The single image can be accessed by url http://mscoco.org/images/[image_id]
