### ISSUE TITLE
What to run after make?

### ISSUE THREAD

**Issue by v3yr0n** [pdollar/coco#28]
Hey, 

Sorry for the lame question, but what do i need to run after the make command for the pythonApi?

Thanks!

**Comment by tylin** [comment]
You can compile and run Python API once you "make all" or "make install"
You can find ipynb demo here for how to use API.
https://github.com/pdollar/coco/blob/master/PythonAPI/pycocoDemo.ipynb

**Comment by v3yr0n** [comment]
OK, thanks!
I was able to run the demo scripts! :)

Question: Can I use this to, for example, get all umbrellas in an image from google for example?

Thanks!

**Comment by tylin** [comment]
That does not sound like possible.
The API only works for images in COCO dataset.

**Comment by v3yr0n** [comment]
Ok, thanks! 
Then how can I run the same scripts that create the annotations files, used in the COCO dataset?

**Comment by ujsyehao** [comment]
@v3yr0n I do not understand your words,it can create the annotations files by *.json

**Comment by ujsyehao** [comment]
@v3yr0n how to run the demo scripts?

**Comment by ujsyehao** [comment]
@tylin Can you tell me how to use API from ipynb demo,i am confused with it .I donnot understand the demo and i cannot run it .
