### ISSUE TITLE
mask.decode 

### ISSUE THREAD

**Issue by RORO11** [pdollar/coco#29]
when I use pycocotools,I receive a error:Process finished with exit code -1073740940 (0xC0000374)(pycaffe in windows),
it's always Abnormal exit at mask.decode,and COCO.showAnn ,But when I used them in ubuntu,it can run normally,so I want  to ask can it use in windows???

**Comment by tylin** [comment]
The MaskAPI has not been tested under windows and might not work with it.

**Comment by RORO11** [comment]
ok,thank you for answer
