### ISSUE TITLE
RLE to segmentation

### ISSUE THREAD

**Issue by huttarichard** [pdollar/coco#33]
Hi there, nice job guys with datasets....
I have one question also regarding closed #23 
Im trying to create new json with segmentation field.

It is little bit hard to find out what this segmentation filed means...

I can get RLE object (but it is probably wrong):

```python
boundsTuples = [(x,y), (x1,y1), ...]

img = Image.new('L', (width, height), 0)
ImageDraw.Draw(img).polygon(boundsTuple, outline=1, fill=1)
mask = np.array(img)
fortran = np.asfortranarray(mask)
encoded = encode(fortran)
# encoded now has {counts, size} fileds
```

how can I convert rle object into segmentation array?

**Comment by tylin** [comment]
You might find .annToMask useful for your use case https://github.com/pdollar/coco/blob/master/PythonAPI/pycocotools/coco.py#L421-L428

**Comment by huttarichard** [comment]
@tylin I have further question, segemntation available datasets are actually polygons ([x, y, x1, y2 .... xn, yn]), is that right?

**Comment by tylin** [comment]
Yes, except for crowd region (iscrowd=1), the annotations were encoded by RLE.

**Comment by huttarichard** [comment]
@tylin got it! thanks!

**Comment by waspinator** [comment]
@tylin iscrowd=1 uses uncompressed RLE. How would you convert a mask to uncompressed RLE?
