### ISSUE TITLE
the strange decrease of coco metrics when modifing the source code in torchvison.model

### ISSUE THREAD

**Issue by Michael-J98** [pdollar/coco#381]
I tried to evaluate my model which is based  on torchvison.model with cocoapi, and here is what I got:

IoU metric: segm
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.965
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.999
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.980
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.250
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.975
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.392
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.969
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.969
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.500
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.978.

Then to filter out the predictions with low scores, I changed the "box_score_thresh" value in its source code from 0.05 to 0.99989(0.9999 is a great threshold from observation). Predictions with low scores were excluded as I wished. However, when I evaluated it again, all the metrics dropped strangely as followed:

IoU metric: segm
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.932
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.960
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.960
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.952
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.388
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.939
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.939
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.958.

Shouldn't they be raised as there are fewer FPs?

Someone can help me? I'm really confused.

**Comment by simaiden** [comment]
Have you found the reason of this?

**Comment by Michael-J98** [comment]
> Have you found the reason of this?

Sadly, not yet☹️

**Comment by simaiden** [comment]
> > Have you found the reason of this?
> 
> Sadly, not yetfrowning_face

I found [this](http://openaccess.thecvf.com/content_ECCV_2018/papers/Kemal_Oksuz_Localization_Recall_Precision_ECCV_2018_paper.pdf) paper where talk about the deficiencies in AP calculation, and some of this are:

> **AP is not confidence-score sensitive**. Since the sorted list of the de-tections is required to calculate AP, a detector generating results in a limited interval will lead to the same AP. As an example, consider only 2 detections with same confidence score in Fig. 1 out of 4 ground truths. Note that setting the confidence scores to any value (i.e. 0.01) leads to the same AP as long as the order is preserved.
**AP does not suggest a confidence score threshold for the best setting of the object detector.** However, in a practical application, detections are usually required to be filtered owing to time limitations. For example, the state-of-the-art online object detector [17] applies a confidence score threshold of 0.8on the SSD method [16] and obtains 12fps in this fashion.

Also. in the PASCAL VOC [paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.157.5766&rep=rep1&type=pdf)

> The intention in interpolating the precision/recall curvein  this  way  is  to  reduce  the  impact  of  the  “wiggles”  inthe precision/recall curve, caused by small variations in theranking of examples. It should be noted that to obtain a highscore, a method must have precision at all levels of recall –this penalises methods which retrieve only a subset of exam-ples with high precision (e.g. side views of cars).


So I think it's a problem of the metric itself, or maybe it's designed in this way to make a very general metric, and depends of your problem use a specific confidence threshold.

Also, instead of re calculate your predictions you can add the argument `threshold` to `loadRes` function:
`cocoDt=cocoGt.loadRes('detection_results.json',threshold=thr)`

In this way you can plot the precision-recall curve of your classes with the following code snippet:

```
cocoEval.evaluate()
cocoEval.accumulate()
cocoEval.summarize()
all_precision = cocoEval.eval['precision']
pr_5 = all_precision[0, :, 0, 0, 2].tolist() # data for IoU@0.5
pr_7 = all_precision[4, :, 0, 0, 2].tolist() # data for IoU@0.7

x = np.arange(0, 1.01, 0.01)
plt.plot(x,pr50)
```
With this i got the following curves for confidence threshold o (standard way) and 0.5
![asd](https://user-images.githubusercontent.com/32749727/77980394-8997fe80-72dd-11ea-94f3-98d2ac13ea0a.jpeg)
![WhatsApp Image 2020-03-30 at 20 31 44(1)](https://user-images.githubusercontent.com/32749727/77980355-74bb6b00-72dd-11ea-9e64-13fde517f693.jpeg)

You can see that the lower the confidence, the lower the detections and thus fewer precision values at high recalls values, so less values to aggregate at the ap calculation.

**Comment by Michael-J98** [comment]
> > > Have you found the reason of this?
> > 
> > 
> > Sadly, not yetfrowning_face
> 
> I found [this](http://openaccess.thecvf.com/content_ECCV_2018/papers/Kemal_Oksuz_Localization_Recall_Precision_ECCV_2018_paper.pdf) paper where talk about the deficiencies in AP calculation, and some of this are:
> 
> > **AP is not confidence-score sensitive**. Since the sorted list of the de-tections is required to calculate AP, a detector generating results in a limited interval will lead to the same AP. As an example, consider only 2 detections with same confidence score in Fig. 1 out of 4 ground truths. Note that setting the confidence scores to any value (i.e. 0.01) leads to the same AP as long as the order is preserved.
> > **AP does not suggest a confidence score threshold for the best setting of the object detector.** However, in a practical application, detections are usually required to be filtered owing to time limitations. For example, the state-of-the-art online object detector [17] applies a confidence score threshold of 0.8on the SSD method [16] and obtains 12fps in this fashion.
> 
> Also. in the PASCAL VOC [paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.157.5766&rep=rep1&type=pdf)
> 
> > The intention in interpolating the precision/recall curvein  this  way  is  to  reduce  the  impact  of  the  “wiggles”  inthe precision/recall curve, caused by small variations in theranking of examples. It should be noted that to obtain a highscore, a method must have precision at all levels of recall –this penalises methods which retrieve only a subset of exam-ples with high precision (e.g. side views of cars).
> 
> So I think it's a problem of the metric itself, or maybe it's designed in this way to make a very general metric, and depends of your problem use a specific confidence threshold.
> 
> Also, instead of re calculate your predictions you can add the argument `threshold` to `loadRes` function:
> `cocoDt=cocoGt.loadRes('detection_results.json',threshold=thr)`
> 
> In this way you can plot the precision-recall curve of your classes with the following code snippet:
> 
> ```
> cocoEval.evaluate()
> cocoEval.accumulate()
> cocoEval.summarize()
> all_precision = cocoEval.eval['precision']
> pr_5 = all_precision[0, :, 0, 0, 2].tolist() # data for IoU@0.5
> pr_7 = all_precision[4, :, 0, 0, 2].tolist() # data for IoU@0.7
> 
> x = np.arange(0, 1.01, 0.01)
> plt.plot(x,pr50)
> ```
> 
> With this i got the following curves for confidence threshold o (standard way) and 0.5
> ![asd](https://user-images.githubusercontent.com/32749727/77980394-8997fe80-72dd-11ea-94f3-98d2ac13ea0a.jpeg)
> ![WhatsApp Image 2020-03-30 at 20 31 44(1)](https://user-images.githubusercontent.com/32749727/77980355-74bb6b00-72dd-11ea-9e64-13fde517f693.jpeg)
> 
> You can see that the lower the confidence, the lower the detections and thus fewer precision values at high recalls values, so less values to aggregate at the ap calculation.

Wow~man, that seems really professional. I’ll take a great look at it. Thanks a lot!!!😙😙😙

**Comment by Fetulhak** [comment]
@Michael-J98   @simaiden
when i decease the value of IOU thresh in coco evaluation the AP and AR values become better and better. is it a correct way to evaluate object detection. How did this happen? the recommended value is iou threshold of 0.5 but in that value I get -1

 Average Precision  (AP) @[ IoU=0.05:0.05 | area=   all | maxDets=100 ] = 0.629
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=500 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=500 ] = -1.000
 Average Precision  (AP) @[ IoU=0.05:0.05 | area= small | maxDets=500 ] = 0.764
 Average Precision  (AP) @[ IoU=0.05:0.05 | area=medium | maxDets=500 ] = 0.844
 Average Precision  (AP) @[ IoU=0.05:0.05 | area= large | maxDets=500 ] = 0.255
 Average Recall     (AR) @[ IoU=0.05:0.05 | area=   all | maxDets= 10 ] = 0.133
 Average Recall     (AR) @[ IoU=0.05:0.05 | area=   all | maxDets=100 ] = 0.703
 Average Recall     (AR) @[ IoU=0.05:0.05 | area=   all | maxDets=500 ] = 0.932
 Average Recall     (AR) @[ IoU=0.05:0.05 | area= small | maxDets=500 ] = 0.912
 Average Recall     (AR) @[ IoU=0.05:0.05 | area=medium | maxDets=500 ] = 0.950
 Average Recall     (AR) @[ IoU=0.05:0.05 | area= large | maxDets=500 ] = 0.429
 Average Precision  (AP) @[ IoU=0.50      | area= small | maxDets=500 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=medium | maxDets=500 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area= large | maxDets=500 ] = -1.000
 Average Precision  (AP) plasmodium @[ IoU=0.05:0.05 | area=   all | maxDets=500 ] = 0.815
 Average Precision  (AP) plasmodium @[ IoU=0.05:0.05 | area= small | maxDets=500 ] = 0.764
 Average Precision  (AP) plasmodium @[ IoU=0.05:0.05 | area=medium | maxDets=500 ] = 0.844
 Average Precision  (AP) plasmodium @[ IoU=0.05:0.05 | area= large | maxDets=500 ] = 0.255
 Average Precision  (AP) plasmodium @[ IoU=0.50      | area=   all | maxDets=500 ] = -1.000
 Average Precision  (AP) plasmodium @[ IoU=0.50      | area= small | maxDets=500 ] = -1.000
 Average Precision  (AP) plasmodium @[ IoU=0.50      | area=medium | maxDets=500 ] = -1.000
 Average Precision  (AP) plasmodium @[ IoU=0.50      | area= large | maxDets=500 ] = -1.000

**Comment by Fetulhak** [comment]
@Michael-J98   @simaiden
when i decease the value of IOU thresh in coco evaluation the AP and AR values become better and better. is it a correct way to evaluate object detection. How did this happen? the recommended value is iou threshold of 0.5 but in that value I get -1

 Average Precision  (AP) @[ IoU=0.05:0.05 | area=   all | maxDets=100 ] = 0.629
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=500 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=500 ] = -1.000
 Average Precision  (AP) @[ IoU=0.05:0.05 | area= small | maxDets=500 ] = 0.764
 Average Precision  (AP) @[ IoU=0.05:0.05 | area=medium | maxDets=500 ] = 0.844
 Average Precision  (AP) @[ IoU=0.05:0.05 | area= large | maxDets=500 ] = 0.255
 Average Recall     (AR) @[ IoU=0.05:0.05 | area=   all | maxDets= 10 ] = 0.133
 Average Recall     (AR) @[ IoU=0.05:0.05 | area=   all | maxDets=100 ] = 0.703
 Average Recall     (AR) @[ IoU=0.05:0.05 | area=   all | maxDets=500 ] = 0.932
 Average Recall     (AR) @[ IoU=0.05:0.05 | area= small | maxDets=500 ] = 0.912
 Average Recall     (AR) @[ IoU=0.05:0.05 | area=medium | maxDets=500 ] = 0.950
 Average Recall     (AR) @[ IoU=0.05:0.05 | area= large | maxDets=500 ] = 0.429
 Average Precision  (AP) @[ IoU=0.50      | area= small | maxDets=500 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=medium | maxDets=500 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area= large | maxDets=500 ] = -1.000
 Average Precision  (AP) plasmodium @[ IoU=0.05:0.05 | area=   all | maxDets=500 ] = 0.815
 Average Precision  (AP) plasmodium @[ IoU=0.05:0.05 | area= small | maxDets=500 ] = 0.764
 Average Precision  (AP) plasmodium @[ IoU=0.05:0.05 | area=medium | maxDets=500 ] = 0.844
 Average Precision  (AP) plasmodium @[ IoU=0.05:0.05 | area= large | maxDets=500 ] = 0.255
 Average Precision  (AP) plasmodium @[ IoU=0.50      | area=   all | maxDets=500 ] = -1.000
 Average Precision  (AP) plasmodium @[ IoU=0.50      | area= small | maxDets=500 ] = -1.000
 Average Precision  (AP) plasmodium @[ IoU=0.50      | area=medium | maxDets=500 ] = -1.000
 Average Precision  (AP) plasmodium @[ IoU=0.50      | area= large | maxDets=500 ] = -1.000

**Comment by simaiden** [comment]
> @Michael-J98 @simaiden
> when i decease the value of IOU thresh in coco evaluation the AP and AR values become better and better. is it a correct way to evaluate object detection. How did this happen? the recommended value is iou threshold of 0.5 but in that value I get -1
> 
> Average Precision (AP) @[ IoU=0.05:0.05 | area= all | maxDets=100 ] = 0.629
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=500 ] = -1.000
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=500 ] = -1.000
> Average Precision (AP) @[ IoU=0.05:0.05 | area= small | maxDets=500 ] = 0.764
> Average Precision (AP) @[ IoU=0.05:0.05 | area=medium | maxDets=500 ] = 0.844
> Average Precision (AP) @[ IoU=0.05:0.05 | area= large | maxDets=500 ] = 0.255
> Average Recall (AR) @[ IoU=0.05:0.05 | area= all | maxDets= 10 ] = 0.133
> Average Recall (AR) @[ IoU=0.05:0.05 | area= all | maxDets=100 ] = 0.703
> Average Recall (AR) @[ IoU=0.05:0.05 | area= all | maxDets=500 ] = 0.932
> Average Recall (AR) @[ IoU=0.05:0.05 | area= small | maxDets=500 ] = 0.912
> Average Recall (AR) @[ IoU=0.05:0.05 | area=medium | maxDets=500 ] = 0.950
> Average Recall (AR) @[ IoU=0.05:0.05 | area= large | maxDets=500 ] = 0.429
> Average Precision (AP) @[ IoU=0.50 | area= small | maxDets=500 ] = -1.000
> Average Precision (AP) @[ IoU=0.50 | area=medium | maxDets=500 ] = -1.000
> Average Precision (AP) @[ IoU=0.50 | area= large | maxDets=500 ] = -1.000
> Average Precision (AP) plasmodium @[ IoU=0.05:0.05 | area= all | maxDets=500 ] = 0.815
> Average Precision (AP) plasmodium @[ IoU=0.05:0.05 | area= small | maxDets=500 ] = 0.764
> Average Precision (AP) plasmodium @[ IoU=0.05:0.05 | area=medium | maxDets=500 ] = 0.844
> Average Precision (AP) plasmodium @[ IoU=0.05:0.05 | area= large | maxDets=500 ] = 0.255
> Average Precision (AP) plasmodium @[ IoU=0.50 | area= all | maxDets=500 ] = -1.000
> Average Precision (AP) plasmodium @[ IoU=0.50 | area= small | maxDets=500 ] = -1.000
> Average Precision (AP) plasmodium @[ IoU=0.50 | area=medium | maxDets=500 ] = -1.000
> Average Precision (AP) plasmodium @[ IoU=0.50 | area= large | maxDets=500 ] = -1.000

The correct way is use the lower iou threshold possible, then you can adjust it to avoid false positives depending of your problem
