### ISSUE TITLE
`segToMask` removed; alternative?

### ISSUE THREAD

**Issue by tomwallis** [pdollar/coco#4]
My student's code calls the `coco.segToMask` method but this has been removed in the new version of the toolbox (see [this commit](https://github.com/pdollar/coco/commit/312d4826abaa3e04430421b265531f50ba895b9e)). What is the recommended replacement for `segToMask`?

**Comment by tylin** [comment]
The coco.segToMask function was replaced by maskApi.  You can use encode/decode functions in mask.py or MaskApi.m for the conversion.  Please see section 3 at http://mscoco.org/dataset/#download for more information.

**Comment by tomwallis** [comment]
Ok, thank you. So if I read the code in `coco.showAnns()` correctly, I could replace 

`mask = coco.segToMask(ann['segmentation'], img['height'], img['width'])`

with 

```
rle = mask.frPyObjects(ann['segmentation'], img['height'], img['width'])
m = mask.decode(rle)
```

(having imported `mask` from pycocotools). Is that correct?

**Comment by tylin** [comment]
Yes, that's correct.

**Comment by tomwallis** [comment]
Great. Also, is it correct that there's now a distinction between annotations stored as polygons and annotations stored as RLE?

**Comment by tylin** [comment]
Now the training and validation annotations have two types of segmentation annotations (1) polygon (object instance) and (2)  uncompressed RLE (crowd).  The MaskApi can be used to convert both polygon and uncompressed RLE to compact RLE format.  Then one can run IoU computation and binary mask conversion with the compact RLE format.  To participate the detection challenge using object segmentation, one needs to store the object masks in RLE format for the detection results.

**Comment by tomwallis** [comment]
Great, thank you for the clarification.
