### ISSUE TITLE
Strange crowd annotations

### ISSUE THREAD

**Issue by nightrome** [pdollar/coco#40]
Hi,

I am experiencing some issues on images with crowd annotations. Sometimes polygons seem to be connected that should not be connected. Below I have created a minimum working example. It shows the code to display the incorrect annotations and I also show the corresponding image. Whereas the round shapes are correct, the entire V shape in the top right should not be there. Is that a known issue?

```
imgId = 000000002963;
cocoApi = CocoApi('instances_train2014.json');
annIds = cocoApi.getAnnIds('imgIds', imgId, 'iscrowd', []);
anns = cocoApi.loadAnns(annIds);
curSegs = anns(end).segmentation;
M = double(MaskApi.decode(curSegs));
imagesc(M)
```

![crowd-annotations](https://cloud.githubusercontent.com/assets/1212780/23801534/c744af14-05b0-11e7-93b8-5338872ec418.png)

![image](http://farm5.staticflickr.com/4014/4442910960_876c3a59cc.jpg)

**Comment by tylin** [comment]
That seems to be annotated by an adversarial worker and didn't get filtered out at the quality check stage.

**Comment by nightrome** [comment]
Haha. Okay, good to hear that it wasn't a mistake on my side :+1:
