### ISSUE TITLE
No module named pycocoevalcap.eval

### ISSUE THREAD

**Issue by WERush** [pdollar/coco#42]
sys.path.append('/home/WERush/code/coco/PythonAPI/')
from pycocotools.coco import COCO
from pycocoevalcap.eval import COCOEvalCap

ImportError: No module named pycocoevalcap.eval

when i run the above code, i get the error "No module named pycocoevalcap.eval". I successfully run the 'make' command in PythonAPI and import the pycocotools.coco. I google the error but get nothing useful.

**Comment by tylin** [comment]
The coco captioning evaluation code is at a different repository: https://github.com/tylin/coco-caption

**Comment by WERush** [comment]
Yes, I have repaired this issue.

Thanks.
