### ISSUE TITLE
cityscapes test error

### ISSUE THREAD

**Issue by wojiaoyanmin** [pdollar/coco#431]
I used cocoapi to evaluate cotyscapes,but I got the following error, I wonder why this happens

DONE (t=0.00s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.00

**Comment by duongphilong1989** [comment]
I got the same error.

**Comment by mmobai** [comment]
> I used cocoapi to evaluate cotyscapes,but I got the following error, I wonder why this happens
> 
> DONE (t=0.00s).
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = -1.000
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = -1.000
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = -1.000
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.00

have you solve this problem? I meet the same today
