### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__mask)

### ISSUE THREAD

**Issue by hjptriplebee** [pdollar/coco#45]
I am using python 3.5.2 to do some experiments and have installed pythonAPI. 
When I import it with "**from pycocotools.coco import COCO**", I get the following error: 
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "/home/hjp/deepLearning/cocoTools/coco/PythonAPI/pycocotools/coco.py", line 55, in &lt;module&gt;
    from . import mask as maskUtils
  File "/home/hjp/deepLearning/cocoTools/coco/PythonAPI/pycocotools/mask.py", line 3, in &lt;module&gt;
    import pycocotools._mask as _mask
ImportError: dynamic module does not define module export function (PyInit__mask)

**Comment by hjptriplebee** [comment]
OK, I have solved it. "make" uses python2 to compile and install cocotools by default. 
So I used "sudo python3 setup.py install" to solve the problem.

**Comment by sara782** [comment]
Could you reiterate what you've done to fix this problem, please?

**Comment by gioipv** [comment]
Halo, this is the steps i did.
first, clone the cocoapi tool
https://github.com/cocodataset/cocoapi
Following the readme.md in this repos. And i use python, so i run
```
cd cocoapi/PythonAPI
make
python3 setup.py install
```
It worked for me.
