### ISSUE TITLE
pycocotools fails to install on python <=3.6

### ISSUE THREAD

**Issue by robin-wayve** [pdollar/coco#468]
Currently if you run `pip install pycocotools` on Python 3.6 (or earlier) you will see something like this:
```
ERROR: Command errored out with exit status 1:
[...]
      File "/tmp/easy_install-i3fx38y0/numpy-1.20.0rc1/setup.py", line 30, in <module>
        package_dir={'pycocotools': 'pycocotools'},
    RuntimeError: Python version >= 3.7 required.
```

`numpy@1.20.0rc1` [came out a few days ago](https://pypi.org/project/numpy/1.20.0rc1/#history) but I couldn't quite figure out why it was being installed.

I unpacked the 2.0.2 release of `pycocotools` from pypi and found this in the `setup.py`
```
setup_requires = [
    'setuptools>=18.0',
    'cython>=0.27.3',
    'numpy',
]
dist.Distribution().fetch_build_eggs(setup_requires)

import numpy as np

ext_modules = [
    Extension(
        'pycocotools._mask',
        sources=['./common/maskApi.c', 'pycocotools/_mask.pyx'],
        include_dirs=[np.get_include(), './common'],
        extra_compile_args=[] if platform.system() == 'Windows' else ['-Wno-cpp', '-Wno-unused-function', '-std=c99'],
    )
]
```
I could see that there is an open dependency on `numpy`, so I tried to look at the source and found different contents which were last changed 3 years ago: https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/setup.py#L1-L27

Possibly related to #416 -- what is going on with the published package on pypi?

**Comment by robin-wayve** [comment]
There's a few differences between this repo and the published package including a `common` folder that includes `gason.cpp  gason.h  maskApi.c  maskApi.h` and these changes:
```
--- pycocotools-2.0.2/pycocotools/coco.py       2020-08-14 19:41:27.000000000 +0100
+++ cocoapi/PythonAPI/pycocotools/coco.py       2020-12-08 15:44:57.804798462 +0000
@@ -81,8 +81,7 @@
         if not annotation_file == None:
             print('loading annotations into memory...')
             tic = time.time()
-            with open(annotation_file, 'r') as f:
-                dataset = json.load(f)
+            dataset = json.load(open(annotation_file, 'r'))
             assert type(dataset)==dict, 'annotation file format {} not supported'.format(type(dataset))
             print('Done (t={:0.2f}s)'.format(time.time()- tic))
             self.dataset = dataset
@@ -315,8 +314,7 @@
         print('Loading and preparing results...')
         tic = time.time()
         if type(resFile) == str or (PYTHON_VERSION == 2 and type(resFile) == unicode):
-            with open(resFile) as f:
-                anns = json.load(f)
+            anns = json.load(open(resFile))
         elif type(resFile) == np.ndarray:
             anns = self.loadNumpyAnnotations(resFile)
         else:
@@ -440,4 +438,4 @@
         """
         rle = self.annToRLE(ann)
         m = maskUtils.decode(rle)
-        return m
+        return m
\ No newline at end of file
```

**Comment by jiyongjung0** [comment]
Hi, I met similar problem and it seems related to [an issue between pip and easyinstall](https://github.com/pypa/pip/issues/6667).
So the recommended resolution seems like migrating the project requirement to `pyproject.toml`.

As an temporary workaround from users-side, I installed numpy with `pip install numpy`(this will install compatible numpy 😄 ) before installing pycocotools and it worked.

**Comment by robin-wayve** [comment]
Since 3.6 is EOL in a week, I'll close this now.

**Comment by robin-wayve** [comment]
got a similar breakage this week because of the release of 1.22
```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
