### ISSUE TITLE
Convert compact RLE to polygon format

### ISSUE THREAD

**Issue by wish2023** [pdollar/coco#476]
I currently have these annotations

**"segmentation":{
          "size":[
             5482,
             7420
          ],
          "counts":"en_[e0ac0cg4\\4fK]2bM]1dNS1nN[1eNn0RO?A>C=C;E;Eh0XOP1QOb0^O;E<_RLYnNh`3SR1[^LbnNaa3lQ1_]LjnN]b3RR1V\\LcnNfc3oR1WZLfmNee3PS1SYLfmNif3SS1TWL[nNhh3WZ1L4L4K5L4K6K4L4K5L5K4L5K4K4M3M3M2O2M3M2N200O01O010O0010O01O00100O0010O01O10O01O1O010O1O00100O1O0010O00000000000001O000000000001O000000000001O00000000000000001O1O1O001O1N101O1O001N101O001N101O001O0O2O001O0O2O00001O0O10000000000000001O000000000000000000000O1000000000000000001O0000000001O00000001O0000000000000001O01O00000000000000000000000000000001O0000000000000000000000000000000000000000000000000000001O000000000000000000000000000000000000000000000000000000000O1000000000000000000000000000000000000000000000000000000000000O10000000000000000000000000000000O10O100000000000000000000000000O1000000000000000000000000O1000000000000O10001O000O1000000O1000000O1000000O1000000O1000000O100000000O1000000O100000000O1000000O100000000O1000000O101O0O100O10000O010O100O100O100O100O100O100O100O100O100O100O100000000O100000001O000O10000000000O100000000000000O100000000O10000O10000O10000O1000000O10000O1000000O01000O1000000O100000000000000000001O000000000O1000000000000000000000000000000O10000000000O10000000001O0O1000000000000O1000000000000O1000000000001O0000000000000000000000000000000000000000000000000000000O2O000000000000000000000O10000000000000000000001O0000000000000000000000000000000000000000000000000000000000000000000O100000000000000000000000000000000000000000000000000000000001O00000000000000000000001O000000000000000000001O001O001O1O001O001O1O001O1O1O001O1O1O1O1O100O1O1O2N1O1O2N1O3M2N3M3L4M3M4L4L4L4L5K5K5K6J7V^N[\\La[1Wk3`N9G9F8I7I6J5K6J4L5K4L4L3M4L4L4L4L5K5K6J6J7H9H<D>B`0@h0XOX4hK[2eMo0QO?A=C<D;E5K5K4L3M4L3M3M3M3L4L4L4L5K5K5K6J9G;D=D=B`0AW1hNg3YLZ2fMP1POb0]Oa0_O`0A>A?B=C<C=D:G;D<D<E:E<D=B`0Aa0_Ob0]Oe0[Oh0WOl0UOP1oNZ1eNcg^V="
       }**

I want to get something like this. Can I convert the compact RLE format to polygon format using mask.py? If so, what functions do I need to use to get such a conversion?

**"segmentation":[
             [
                1485.8382858000696,
                497.0831564962864,
                2538.697008928284,
                431.28022196888924,
                2696.6283068284392,
                2681.7719365358353,
                1643.7775838784873,
                2747.574352309108,
                1485.8382858000696,
                497.0831564962864
             ]
          ],**

**Comment by jkamalu** [comment]
Did you figure this out? I have the same problem.

**Comment by wish2023** [comment]
Yes, I first convert the compact RLE to a masked array:

```
import pycocotools.mask as mask
maskedArr = mask.decode(compactRLESegmentation)
```

then convert this to polygon format

```
def polygonFromMask(maskedArr): # https://github.com/hazirbas/coco-json-converter/blob/master/generate_coco_json.py

        contours, _ = cv2.findContours(maskedArr, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

        segmentation = []
        for contour in contours:
            # Valid polygons have >= 6 coordinates (3 points)
            if contour.size >= 6:
                segmentation.append(contour.flatten().tolist())
        RLEs = mask.frPyObjects(segmentation, maskedArr.shape[0], maskedArr.shape[1])
        RLE = mask.merge(RLEs)
        # RLE = mask.encode(np.asfortranarray(maskedArr))
        area = mask.area(RLE)
        [x, y, w, h] = cv2.boundingRect(maskedArr)

        return segmentation[0] #, [x, y, w, h], area
```

**Comment by pcicales** [comment]
This solution only returns the first polygon generated. RLEs can encode multiple polygons (crowded), so you will need to return all polygons to get an exact match to the original mask. Additionally, if you want to compute area, I recommend computing it manually, as the area computation from pycocotools computes it using contours, which is slightly inaccurate. Here's what I use:

```
import pycocotools.mask as mask
maskedArr = mask.decode(compactRLESegmentation)
area = float((maskedArr > 0.0).sum())
def polygonFromMask(maskedArr):
  # adapted from https://github.com/hazirbas/coco-json-converter/blob/master/generate_coco_json.py
  contours, _ = cv2.findContours(maskedArr, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
  segmentation = []
  valid_poly = 0
  for contour in contours:
  # Valid polygons have >= 6 coordinates (3 points)
     if contour.size >= 6:
        segmentation.append(contour.astype(float).flatten().tolist())
        valid_poly += 1
  if valid_poly == 0:
     raise ValueError
  return segmentation
```
