### ISSUE TITLE
AP is 0 for *segm* but nearly 1 for *bbox*

### ISSUE THREAD

**Issue by Shakesbeer333** [pdollar/coco#478]
I got nearly perfect predictions by visualizing the inferenced images. Also the bbox AP shows good result. However, the segm AP is 0. How is that possible? In previous issues someone wrote that the area might be wrong. In my case, it's the number of pixels of the segmentation mask. So this shouldn't be the problem. 

My segmentation format is [[x1,x1, x2, x2,y2, ...]]

Any suggestions?

**Comment by Shakesbeer333** [comment]
Problem solved. Problem was the format of my segmentation.

**Comment by visbec** [comment]
@Shakesbeer333 I'm facing exactly the same problem. 

I'd tried the following segmentation formats:
[[x1,y1,x2,y2,x3,y3,x4,y4]] -> returns zero metrics
[[x1,y1],[x2,y2],[x3,y3],[x4,y4]] -> causes Exception in COCOeval itself

Any chance you could provide the working segmentation format?

**Comment by Shakesbeer333** [comment]
My problem was that my labels included every single pixel of the segmentation mask. Reducing it to the contour line pixel (openCV provides a method for that) not only massively reduced the memory needed to store the labels but also solved my above mentioned problem. I hope that helps @visbec

**Comment by visbec** [comment]
Thanks for your fast answer. Sadly this does not solve my problem. Will look into this on my own.

**Comment by jjbuitrago** [comment]
Were you able to solve it @visbec ??

**Comment by visbec** [comment]
@jjbuitrago Sorry for the late response, I was on vacation ;) Sadly I do not remember the exact solution to the probleme. It was more like a workaround. In my case the segmentation masks corresponded to roughly bounding boxes, so I converted all masks (labels and model predictions) to bounding boxes and evaluated them.
