### ISSUE TITLE
Miscalculation of bounding box?

### ISSUE THREAD

**Issue by ghostcow** [pdollar/coco#5]
Hello, in line 307 of the coco.py code:

https://github.com/pdollar/coco/blob/master/PythonAPI/pycocotools/coco.py#L307

When converting x, y, width, height to x1, x2, y1, y2 when loading a bounding box result, 
it should be x2 = x + width - 1, y2 = y + height - 1 to take into account the extra pixel from the addition.

i.e. x1, x2, y1, y2 = [bb[0], bb[0]+bb[2]-1, bb[1], bb[1]+bb[3]-1]

**Comment by pdollar** [comment]
Actually, the calculation is correct, we simply use a different convention then ImageNet/PASCAL Matlab code. Specifically, the x and y coordinates are 0-indexed absolute coordinates (floats) obtained from user mouse clicks, not integer pixel locations. In our convention, a bounding box spanning the first pixel would have x1=y1=0, x2=y2=1. In the PASCAL convention the same bounding box would have x1=x2=y1=y2=1. When cropping pixels from the image you need to keep this in mind -- in Matlab use I(y1+1:y1+y2,x1+1:x1+x2) to crop the corresponding box from I (note the +1 for the start position).
