### ISSUE TITLE
DeprecationWarning about np.float in numpy>=1.20

### ISSUE THREAD

**Issue by ZwwWayne** [pdollar/coco#528]
Hi there,

I am using the pycocotools and find the deprecation warning with numpy>1.20. It seems the pycocotools should use either `np.float64` or simply use `float` when specifying the type. Would the team like to update it to make it compatible with the new NumPy version?
![image](https://user-images.githubusercontent.com/40779233/125147938-6820f600-e161-11eb-86c1-e00b8fd9290e.png)

**Comment by ppwwyyxx** [comment]
This was now fixed in the pypi version.
