### ISSUE TITLE
precision metric comes out wrong

### ISSUE THREAD

**Issue by RSly** [pdollar/coco#55]
Hi,

I am encountering an inaccurate case with the precision metric.

I have created a simple test (files attached): 
[coco_problem.zip](https://github.com/pdollar/coco/files/1074616/coco_problem.zip)
* the ground_truth.json has one image and one bbx annotated for category 1
* the results.json has two bounding boxes, one for a perfect detection (category 1), and the next for a large  false alarm (category 2) .
* I run the following code

from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

cocoGt=COCO('/ssd2/ground_truth.json')
cocoDt=cocoGt.loadRes('/ssd2/results.json')
cocoEval = COCOeval(cocoGt,cocoDt,'bbox')

cocoEval.evaluate()
cocoEval.accumulate()
cocoEval.summarize()

=> it happens that the api returns, precision and recall to be both 1 which is wrong, since in this case recall should be 1 but precision should be much less than 1 since we have a clear false alarm 

am I missing something here or is this a bug?

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 1.000

**Comment by mohammad-py** [comment]
Hey @RSly. Did you solve above problem? I have written following script which got same result like you! In my script, resFile is a numpy array which has detection results. In each row of `resFile` there are these values: [`ImageID, x1,y1, w, h, score, class`]

```
cocoGt=COCO('./annotations/image_info_test-dev2015.json')
imgIds = resFile[:,0].tolist()
imgIds = list(set(imgIds))
cocoDt=cocoGt.loadRes(resFile)
annType = 'bbox'
cocoEval = COCOeval(cocoGt,cocoDt,annType)
cocoEval.params.imgIds  = imgIds
cocoEval.evaluate()
cocoEval.accumulate()
cocoEval.summarize()
```
and here is the output:
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
```
Could you please tell me what is wrong?

**Comment by RSly** [comment]
@mohammad-py, actually your case is very different 

=> you get -1 which is not a possible value for precision/rercall, instead it is a flag to tell that a case doesn't apply.  

for example if you have only a large object in your image, naturally precision and recall comes out -1 for the case of 'small' and 'medium' objects telling you that there is no such objects. Also it can happen when you miss give imgIds, etc...

**Comment by tylin** [comment]
@RSly thanks for explaining meaning of -1 AP to @mohammad-py.
In your case, the ground truth annotation contains single annotation of category 1.
In such case, the evaluation program would ignore category 2 entirely since it is undefined to compute PR curve for category 2.

**Comment by RSly** [comment]
hi @tylin, thanks for the explanation, you closed this issue too fast :)

I still think there is a problem with the current calculation of precision. here ia another case using the coco validation sets and my attached results42.json. 
[results42.zip](https://github.com/pdollar/coco/files/1088071/results42.zip)

so again I have put a perfect detection on the dog, and a large false alarm next to the dog. you can see that again average recall and precision are both perfect at 1.0 

from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval
cocoGt=COCO('./coco/annotations/instances_val2014.json')
cocoDt=cocoGt.loadRes('./results42.json')
cocoEval = COCOeval(cocoGt,cocoDt,'bbox')
cocoEval.params.imgIds = [42]
cocoEval.evaluate()
cocoEval.accumulate()
cocoEval.summarize()

=> for completeness, I summarized all observations regarding these metrics here: https://github.com/pdollar/coco/issues/56
