### ISSUE TITLE
Architecture incompatibility on M1 Mac (ARM architecture), even when simulating Intel-x64 architecture with Rosetta

### ISSUE THREAD

**Issue by davidpomerenke** [pdollar/coco#561]
Hi, 

I'm on a Macbook with M1 (Apple ARM architecture) and I've tried running the following Python code using the [layoutparser](https://layout-parser.github.io/) library, which indirectly uses `pycocotools`:

```python
import layoutparser as lp
lp.Detectron2LayoutModel()
```

And I've received the error:

```
[...]
ImportError: 
dlopen([...]/.venv/lib/python3.9/site-packages/pycocotools/_mask.cpython-39-darwin.so, 0x0002): 
tried: 
'[...]/.venv/lib/python3.9/site-packages/pycocotools/_mask.cpython-39-darwin.so' 
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), 
'/usr/local/lib/_mask.cpython-39-darwin.so' (no such file), 
'/usr/lib/_mask.cpython-39-darwin.so' (no such file)
```

The crucial info for me seems to be `[...] is an incompatible architecture (have 'x86_64', need 'arm64e') [...]`. Indeed, I am using the Apple ARM architecture, and sometimes it is not supported by some software. This is usually solved by using Rosetta, which simulates an Intel-x64 architecture. So I start a terminal with Rosetta (`arch -x86_64 zsh`), create a new virtual environment, make a fresh install of the dependencies, and try to run the code again ...

... and I receive the same error that I had also had without Rosetta: 

`[...] is an incompatible architecture (have 'x86_64', need 'arm64e') [...]` 🥲

I've double-checked that Rosetta is really activated: 

```bash
> uname -m
x86_64
```

Rosetta seems to be working. And yet, according to the error message, it seems not to be working.

Any ideas what could be the underlying problem, and how I could go about fixing it?

**Comment by davidpomerenke** [comment]
My bad, I was using a Python version for the wrong architecture.

**Comment by th1nk1ng0utl0ud** [comment]
how did you solved this issue?, im getting the same error, while trying to use layout parser with my M1 Mac, but I don't know how to install the packages to fix it.

**Comment by davidpomerenke** [comment]
@DaniluFx Have a look at this Stackoverflow reply, I think it solved exactly this problem:

https://stackoverflow.com/a/70253434/10190810
