### ISSUE TITLE
CocoUtils.convertPascalGt error

### ISSUE THREAD

**Issue by jwnsu** [pdollar/coco#57]
trying to convert pascal format GT to coco json format by invoking CocoUtils.convertPascalGt in Matlab (version: 2014b) command window, got following error: 
"Converting PASCAL VOC dataset...     Undefined function or variable 'VOCinit'.

Error in CocoUtils.convertPascalGt (line 43)
      VOCinit; C=VOCopts.classes'; catsMap=containers.Map(C,1:length(C));"

Not familiar with Matlab. How to overcome this error?

Also, anyone got python script for the same functionality?

Thanks!

**Comment by tylin** [comment]
You can download converted PASCAL from the COCO external page.
http://mscoco.org/external/
It's near the bottom of the page.

**Comment by jwnsu** [comment]
thx, the issue is resolved.

**Comment by ChongZhangZC** [comment]
I want to use my own data with annotations of PASCAL format. How can I debug this error?

Thanks！

**Comment by blateyang** [comment]
I have met the same problem and I also want to use my own datasets with annotations of PASCAL format. Have you solved the problem? @ChongZhangZC

**Comment by blateyang** [comment]
I have solved this problem through search the Internet. The error means that VOCcode folder (containing VOCinit.m) under the VOCdevkit  is missing. You should check whether you own datasets containing VOCdevkit folder. @ChongZhangZC
