### ISSUE TITLE
Convert from coco_instances to coco_stuff

### ISSUE THREAD

**Issue by andreaceruti** [pdollar/coco#581]
Anyone has faced this problem? What I would like to do is to change my JSON file in the object detection format to the stuff format, so I can do semantic segmentation evaluation on my model.

**Comment by engrjav** [comment]
@andreaceruti  did you manage to do this? i want to convert my json result file to png format for training another model

**Comment by andreaceruti** [comment]
@engrjav If you want to change your polygons annotation to binary mask file just use opencv fill poly as in this [example](https://stackoverflow.com/questions/19222343/filling-contours-with-opencv-python#:~:text=think%20what%20you%20are%20looking%20for%20is%20cv2.fillPoly%2C%20which%20fills%20the%20area%20bounded%20by%20one%20or%20more%20polygons.%20This%20is%20a%20simple%20snippet%2C%20I%20generate%20a%20contour%20of%20four%20points%20representing%20vertices%20of%20a%20square%2C%20then%20I%20fill%20the%20polygon%20with%20a%20white%20color.)
