### ISSUE TITLE
How should I set the "area" for custom annotations if I am not going to do segmentation tasks?

### ISSUE THREAD

**Issue by starsong98** [pdollar/coco#604]
Hello, I am currently trying to perform object detection on a custom dataset, and I am in the middle of creating custom annotations in standard COCO format for said dataset.

While trying to run standard DETR on this annotation, I have encountered a field named "area", which apparently means area used for segmentation.

However, my current research project specifically excludes all forms of segmentation, focusing purely on detection tasks.
Yet the evaluateImg function from COCO API's coco_eval.py seems to specifically demand the "area" field, and for now I cannot find any way around this other than at least assigning some placeholder value or modifying the coco API source code.

In this case, how should I compute the "area" field? Or am I understanding something wrong about the "area" field?

**Comment by erikdao** [comment]
@starsong98 Hi, did you find the solution to this question? I'm doing something similar and have the same question.

**Comment by VtojeC** [comment]
In case of pure detection with bounding boxes evaluation Segmentation can be empty. Segmentation in overall is a list of verticies of the field that covers the object entirely. 
Bounding boxes AREA is a width*height.

**Comment by starsong98** [comment]
I have done some studies, and it appears that you can just write the area of the bounding box in this case.

I could get my code (actually just DETR's official implementation) to run properly with that, so I am closing this case.
