### ISSUE TITLE
Support download resume for train2014.zip

### ISSUE THREAD

**Issue by vadimkantorov** [pdollar/coco#64]
curl prints:
```
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
```

when trying to resume download of 13Gb-sized train2014.zip from official `http://msvocds.blob.core.windows.net/coco2014/train2014.zip`.

wget fails to resume as well which is really unfortunate when such a big download breaks.

**Comment by tylin** [comment]
We added a new feature to download individual image through "gsutil rsync". It is recommended especially when downloading big file is problematic. Please see http://cocodataset.org/dataset.htm#download for more details.

**Comment by vadimkantorov** [comment]
thanks!

**Comment by shubhambagwari** [comment]
still facing the same problem.
