### ISSUE TITLE
loadImgs fails for numpy dtypes

### ISSUE THREAD

**Issue by phil0stine** [pdollar/coco#7]
Making a minor adjustment to the [pycocoDemo](https://github.com/pdollar/coco/blob/master/PythonAPI/pycocoDemo.ipynb) will demonstrate the issue. 

In cell 5 (removing randomness for the sake of simplicity), we have
```python
catIds = coco.getCatIds(catNms=['person','dog','skateboard']);
imgIds = coco.getImgIds(catIds=catIds );
img = coco.loadImgs(imgIds[0])[0]
```
If we change ```imgIds``` to be a numpy array (of any int or uint dtype), the same code fails with ```'NoneType' object has no attribute '__getitem__'```
```python
catIds = coco.getCatIds(catNms=['person','dog','skateboard']);
imgIds = np.array(coco.getImgIds(catIds=catIds ), dtype=np.int64);
img = coco.loadImgs(imgIds[0])[0]
```
Beside the difference in datatype, the input is the same for the two cases. Seems like it might be a quick fix but I cannot find exactly where to look.

**Comment by tylin** [comment]
The API now supports python list as input.
You can create a python list from numpy array and send it to API function.
Or you can add numpy support for the function loadImgs here
https://github.com/pdollar/coco/blob/master/PythonAPI/pycocotools/coco.py#L223

**Comment by phil0stine** [comment]
Ok I will look into adding numpy support for ```loadImgs```, however your first proposed solution, creating a python list from a numpy array, also fails. 

When converting to a Python list, the list elements have a new type, ```np.int64``` instead of a Python ```int```, and the function call fails.
