### ISSUE TITLE
mask.py -> encode, Python2 vs Python3 discrepency

### ISSUE THREAD

**Issue by vchiley** [pdollar/coco#70]
I want to take the output of my segmentation network and put it through a eval script modeled after coco/PythonAPI/pycocoEvalDemo.ipynb. 
To do this my input into the script would need to be of the form found in coco/results/instances_val2014_fakesegm100_results.json.
To get the RLE segmentations (i.e. ```"segmentation":{"size":[478,640],"counts":"VQi31m>0O2N100O100O2N100O1000..."}```) I used the encode() method found in mask.py

if `segm = mask.encode(mask)`

using Python2:
type(segm['conts']) is <type 'str'>
using Python3:
type(segm['conts']) is <class 'bytes'>

my problem comes in when I want to write `segm` to a json file. I get:
```
*** TypeError: b']f3[8e70000000000000000000000000000000000000000000000000000000000000cY\\9' is not JSON serializable
```
where that string is `seg['counts']` output by `encode(mask)`

Question: why the discrepency? How do I write `segm` to a json file? can i just convert `segm['conts']` using `str(segm['conts'])` or do I need a specific encoding?

**Comment by tylin** [comment]
The discrepancy is because byte string is handled differently in Python 2 and Python 3. To get around this, you can decode the bytes string to ascii string and dump it in Python 3:
```
rle['counts'] = rle['counts'].decode('ascii')
```

**Comment by vchiley** [comment]
Wow just spent some looking at this, figured out I should do `rle['counts'] = str(rle['counts'], "utf-8")` then was going to go post the solution to my own question only to realize your equivalent solution has been there for hours already... ha

**Comment by gaussiangit** [comment]
I get 'TypeError: Object of type 'uint32' is not JSON serializable' even after I make it to ascii. Any solution ?

**Comment by rodneylalonde-aptiv** [comment]
Try this... https://github.com/cocodataset/cocoapi/issues/91

> @tylin I get 'TypeError: Object of type 'uint32' is not JSON serializable' even after I make it to ascii. Any solution ?

Try this... https://github.com/cocodataset/cocoapi/issues/91
