### ISSUE TITLE
Visualizing Result Anns

### ISSUE THREAD

**Issue by vchiley** [pdollar/coco#71]
Is there a good tutorial for visualizing the res annotations?
In the same way `pycocoEvalDemo.ipynb` evaluates the res annotations, can those res annotations be plotted similar to how `pycocoDemo.ipynb` load and display instance annotations?
This would be useful for visualizing our predicted annotations.

In general can this be done / how?

**Comment by tylin** [comment]
You can load results into coco object by
```
cocoDt=cocoGt.loadRes(resFile)
```
then use the same API to visualize results.

**Comment by yuy01** [comment]
I get my human keypoints detection result whose data structure is defined by MSPN network, how to plot result?
