### ISSUE TITLE
Windows support for python API

### ISSUE THREAD

**Issue by willyd** [pdollar/coco#9]
Please add windows support. Currently it is impossible to compile the python API with MSVC without modifications. I have made some modifications to fix the build. They can be viewed at https://github.com/pdollar/coco/compare/master...willyd:windows?expand=1.

**Comment by pdollar** [comment]
We will not be providing Windows support. Thanks and good luck!

**Comment by alexiskattan** [comment]
@willyd  thank you!!!

**Comment by monezi** [comment]
I just remove 'Who-cpp' and 'Wno-unused-function' (in extra_compile_args) from setup.py and it works on windows 10.

**Comment by HarshalGarg** [comment]
https://github.com/philferriere/cocoapi

cocoapi with windows support

**Comment by HarshalGarg** [comment]
https://github.com/philferriere/cocoapi

coco api with windows support

**Comment by CHAMOD** [comment]
@HarshalGarg  worked nicely

**Comment by yanfengliu** [comment]
The lack of support for Python API on Windows can be fixed by opening `setup.py` and removing the line `extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'],` and then running `python setup.py build_ext install`

**Comment by DuaneNielsen** [comment]
You guys realize that one of your key sponsors is Microsoft, right?

**Comment by yanfengliu** [comment]
> yanfengliu your solution worked for me, thanks for sharing it!

You are very welcome.

**Comment by Minxiangliu** [comment]
@yanfengliu I follow your step to build on Windows10 but I can't work.
Do you have any suggestions?
error message:
```
D:\cocoapi-master\cocoapi-master\PythonAPI>python setup.py build_ext install
running build_ext
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    ext_modules= ext_modules
  File "C:\Users\stust\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\stust\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\stust\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\stust\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\stust\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
    _build_ext.run(self)
  File "C:\Users\stust\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\stust\Anaconda3\lib\distutils\command\build_ext.py", line 308, in run
    force=self.force)
  File "C:\Users\stust\Anaconda3\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "C:\Users\stust\Anaconda3\lib\distutils\cygwinccompiler.py", line 285, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "C:\Users\stust\Anaconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
    if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()
```

**Comment by yanfengliu** [comment]
@Minxiangliu I did some searching with the keyword 

> if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()

and it seems that this issue is not particularly related to MSCOCO. You might find [this](https://stackoverflow.com/questions/48764602/cygwincompiler-typeerror-not-supported-between-instances-of-nonetype-and) or [this](https://stackoverflow.com/questions/24683305/python-cant-install-packages-typeerror-unorderable-types-nonetype-str) helpful though.

**Comment by potoo0** [comment]
> The lack of support for Python API on Windows can be fixed with the following steps:
> 
> 1. Open `setup.py`
> 2. Remove the line `extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'],`
> 3. Run`python setup.py build_ext install`

Excellent, it works. Thanks.

**Comment by dmitry-akimov-dXgjvQjNiMuVYecJ** [comment]
@pdollar 

> We will not be providing Windows support. Thanks and good luck!

Thank you and good luck to you too, a kind colleague! We need more people like you in the industry. Thank you very much!

**Comment by dmitry-akimov-dXgjvQjNiMuVYecJ** [comment]
So, basically, @pdollar does not want to support Windows _out of principle_, even though it requires changing _one line of code_.

> We will not be providing Windows support. Thanks and good luck!

Again, @pdollar thank you very much, and good luck! We definitely need more people like you.

**Comment by maria-mh07** [comment]
I am following the steps of @yanfengliu (for Python API on Windows). But I get the following error:
fatal error C1083: Cannot open file include: 'math.h': No such file or directory
Any help?

**Comment by rafwaf** [comment]
Hi @pdollar,
Obviously you don't owe us (the users of cocoAPI) any answers, and what you contribute to this project and which OS's you support is totally up to you and/or your employer... but, may we ask why is it not supported? what is the rationale? Is it not spreading resources too thin, committing to support more OS's? I'm merely curious about this. Thanks in advance.

p.s. to anyone who may care: @yanfengliu 's solution worked for me to and seems to be the easiest/fastest fix.

**Comment by quaesitor-scientiam** [comment]
@yanfengliu worked perfectly on Windows 10 Pro 1909  with VS 2019 installed and Python 3.7.4

**Comment by anonymouss** [comment]
> https://github.com/philferriere/cocoapi
> 
> cocoapi with windows support

I installed it successfully with this repo on Windows 10

Full steps:
1. install any dependency if missing like cython, etc.
2. install [Visual C++ 14/2015 build tools](http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe), NOTE: **window 10 SDK** is required to be selected if choose custom option (or windows 8.1 SDK depends on your system)
3. `pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI`

**Comment by tirthraj13** [comment]
(base) C:\Users\tmcde>pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\tmcde\appdata\local\temp\pip-req-build-77lgppkj
  Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj'
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-req-build-77lgppkj\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-req-build-77lgppkj\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\tmcde\AppData\Local\Temp\pip-wheel-38f65ymy'
       cwd: C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.7\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.7\pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\pycocotools
  creating build\temp.win-amd64-3.7\common
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\tmcde\anaconda3\lib\site-packages\numpy\core\include -I../common -Ic:\users\tmcde\anaconda3\include -Ic:\users\tmcde\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools/_mask.obj
  _mask.c
  c:\users\tmcde\anaconda3\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-req-build-77lgppkj\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-req-build-77lgppkj\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI\setup.py", line 25, in <module>
      cythonize(ext_modules)
    File "c:\users\tmcde\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 966, in cythonize
      aliases=aliases)
    File "c:\users\tmcde\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 810, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "c:\users\tmcde\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 109, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pycocotools/_mask.pyx' doesn't match any files
  ----------------------------------------
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
    Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-req-build-77lgppkj\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-req-build-77lgppkj\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tmcde\AppData\Local\Temp\pip-record-zmu70pen\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tmcde\anaconda3\Include\pycocotools'
         cwd: C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI
    Complete output (9 lines):
    running install
    running build
    running build_py
    running build_ext
    building 'pycocotools._mask' extension
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\tmcde\anaconda3\lib\site-packages\numpy\core\include -I../common -Ic:\users\tmcde\anaconda3\include -Ic:\users\tmcde\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools/_mask.obj
    _mask.c
    c:\users\tmcde\anaconda3\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-req-build-77lgppkj\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\tmcde\\AppData\\Local\\Temp\\pip-req-build-77lgppkj\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tmcde\AppData\Local\Temp\pip-record-zmu70pen\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tmcde\anaconda3\Include\pycocotools' Check the logs for full command output.
---------------------------------------------------------------------------------------------------------
i still facing this problem . so, plz help me to overcome this issue.

**Comment by TheVIbhav** [comment]
> ## (base) C:\Users\tmcde>pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
> Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
> Cloning https://github.com/philferriere/cocoapi.git to c:\users\tmcde\appdata\local\temp\pip-req-build-77lgppkj
> Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj'
> Building wheels for collected packages: pycocotools
> Building wheel for pycocotools (setup.py) ... error
> ERROR: Command errored out with exit status 1:
> command: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI\setup.py'"'"'; **file**='"'"'C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\tmcde\AppData\Local\Temp\pip-wheel-38f65ymy'
> cwd: C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI
> Complete output (20 lines):
> running bdist_wheel
> running build
> running build_py
> creating build
> creating build\lib.win-amd64-3.7
> creating build\lib.win-amd64-3.7\pycocotools
> copying pycocotools\coco.py -> build\lib.win-amd64-3.7\pycocotools
> copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.7\pycocotools
> copying pycocotools\mask.py -> build\lib.win-amd64-3.7\pycocotools
> copying pycocotools__init__.py -> build\lib.win-amd64-3.7\pycocotools
> running build_ext
> building 'pycocotools._mask' extension
> creating build\temp.win-amd64-3.7
> creating build\temp.win-amd64-3.7\Release
> creating build\temp.win-amd64-3.7\Release\pycocotools
> creating build\temp.win-amd64-3.7\common
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\tmcde\anaconda3\lib\site-packages\numpy\core\include -I../common -Ic:\users\tmcde\anaconda3\include -Ic:\users\tmcde\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools/_mask.obj
> _mask.c
> c:\users\tmcde\anaconda3\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
> ## ERROR: Failed building wheel for pycocotools
> Running setup.py clean for pycocotools
> ERROR: Command errored out with exit status 1:
> command: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI\setup.py'"'"'; **file**='"'"'C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' clean --all
> cwd: C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj
> Complete output (11 lines):
> Traceback (most recent call last):
> File "", line 1, in
> File "C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI\setup.py", line 25, in
> cythonize(ext_modules)
> File "c:\users\tmcde\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 966, in cythonize
> aliases=aliases)
> File "c:\users\tmcde\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 810, in create_extension_list
> for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
> File "c:\users\tmcde\anaconda3\lib\site-packages\Cython\Build\Dependencies.py", line 109, in nonempty
> raise ValueError(error_msg)
> ValueError: 'pycocotools/_mask.pyx' doesn't match any files
> ## ERROR: Failed cleaning build dir for pycocotools
> Failed to build pycocotools
> Installing collected packages: pycocotools
> Running setup.py install for pycocotools ... error
> ERROR: Command errored out with exit status 1:
> command: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI\setup.py'"'"'; **file**='"'"'C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\tmcde\AppData\Local\Temp\pip-record-zmu70pen\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tmcde\anaconda3\Include\pycocotools'
> cwd: C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI
> Complete output (9 lines):
> running install
> running build
> running build_py
> running build_ext
> building 'pycocotools._mask' extension
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\tmcde\anaconda3\lib\site-packages\numpy\core\include -I../common -Ic:\users\tmcde\anaconda3\include -Ic:\users\tmcde\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.7\Release\pycocotools/_mask.obj
> _mask.c
> c:\users\tmcde\anaconda3\include\pyconfig.h(203): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2
> ----------------------------------------
> ERROR: Command errored out with exit status 1: 'c:\users\tmcde\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI\setup.py'"'"'; **file**='"'"'C:\Users\tmcde\AppData\Local\Temp\pip-req-build-77lgppkj\PythonAPI\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\tmcde\AppData\Local\Temp\pip-record-zmu70pen\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tmcde\anaconda3\Include\pycocotools' Check the logs for full command output.
> i still facing this problem . so, plz help me to overcome this issue.

i am also facing a similar issue. Anyone has a solution to this?

**Comment by AdminQiang123** [comment]
> Windows 上缺乏对 Python API 的支持可以通过以下步骤修复：
> 
> 1. 打开 `setup.py`
> 2. 删除该行 `extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'],`
> 3. 跑步`python setup.py build_ext install`

Thanks

**Comment by lesliewubbel** [comment]
Please add in this support already users fixed why not just change the line?

**Comment by pdollar** [comment]
I'm no longer maintaining this code, but I'd be supportive of the change. (The bigger issue is this codebase isn't actively supported any longer...)

**Comment by Robotatron** [comment]
> > https://github.com/philferriere/cocoapi
> > cocoapi with windows support
> 
> I installed it successfully with this repo on Windows 10
> 
> Full steps:
> 
> 1. install any dependency if missing like cython, etc.
> 2. install [Visual C++ 14/2015 build tools](http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe), NOTE: **window 10 SDK** is required to be selected if choose custom option (or windows 8.1 SDK depends on your system)
> 3. `pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI`

Does not work:

`Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\sergiy.\appdata\local\temp\pip-req-build-cdg943ek
  Running command git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Sergiy.\AppData\Local\Temp\pip-req-build-cdg943ek'
  Resolved https://github.com/philferriere/cocoapi.git to commit 2929bd2ef6b451054755dfd7ceb09278f935f7ad
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\coco.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\mask.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\__init__.py -> build\lib.win-amd64-3.8\pycocotools
      running build_ext
      building 'pycocotools._mask' extension
      creating build\temp.win-amd64-3.8
      creating build\temp.win-amd64-3.8\common
      creating build\temp.win-amd64-3.8\Release
      creating build\temp.win-amd64-3.8\Release\pycocotools
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\../common/maskApi.obj
      maskApi.c
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.8\Release\pycocotools/_mask.obj
      _mask.c
      c:\users\sergiy.\miniconda3\envs\mmdet\include\pyconfig.h(205): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Sergiy.\AppData\Local\Temp\pip-req-build-cdg943ek\PythonAPI\setup.py", line 25, in <module>
          cythonize(ext_modules)
        File "C:\Users\Sergiy.\Miniconda3\envs\mmdet\lib\site-packages\Cython\Build\Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "C:\Users\Sergiy.\Miniconda3\envs\mmdet\lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\Sergiy.\Miniconda3\envs\mmdet\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'pycocotools/_mask.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
  Running setup.py install for pycocotools ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pycocotools did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running install
      C:\Users\Sergiy.\Miniconda3\envs\mmdet\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      building 'pycocotools._mask' extension
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\../common/maskApi.obj
      maskApi.c
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.8\Release\pycocotools/_mask.obj
      _mask.c
      c:\users\sergiy.\miniconda3\envs\mmdet\include\pyconfig.h(205): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycocotools

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by WASasquatch** [comment]
Similar issues with the adding the fix here and the fork project

```
      pycocotools/_mask.c(32): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

I have 2015 build tools as well, but it doesn't seem to be using them over 2019. 

It's pretty embarrassing how much stuff relies on pycocotools and it's pretty much abandoned without any real support for Windows.

**Comment by cannacak** [comment]
Here is the solution worked for me : Download the file beneath
https://drive.google.com/file/d/1KI0sfJBw8moRioFcLQrziS-BOXpy_KZt/view?usp=sharing

Copy these files to C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages

In case you still can not solve the problem, do not hesitate to mail me !
